# These are supported funding model platforms

github: [martl]
patreon: martl
open_collective: martl
ko_fi: martl
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: check-den-fakt
liberapay: martl
issuehunt: martl
otechie: martina.freundorfer@digitalcareerinstitute.org
custom: ['https://www.paypal.com/paypalme2/heartbeaz/5']
